name: allure-report
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install --without dev
        working-directory: ${{ inputs.working-directory }}
      - name: Prepare Allure history
        run: |
          cd ..
          mkdir -p ${{ vars.ALLURE_RESULTS_PATH }}
      - name: Run tests with pytest
        run: |
          python -m pytest -v --gherkin-terminal-reporter -s --tags="${{
          github.event.inputs.tags }}" --color=yes --alluredir=../${{
          vars.ALLURE_RESULTS_PATH }}
      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Allure report action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: ${{ vars.ALLURE_RESULTS_PATH }}
          allure_history: allure-history
          keep_reports: 5
      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
